name: Deploy to GitHub Pages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-blog.yaml
    with:
      output-path: github-pages

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: ${{ github.ref_name == github.event.repository.default_branch }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: blog-build
          path: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
